      	INSERT INTO INSTALLATIONDEPLOYMENT
			   (INSTALLATIONGUID
			   ,DEPLOYMENTGUID
			   ,ISAVAILABLE
			   ,AVAILABLEUTCDATE
			   ,UPDATEDUTCDATE
			   ,LASTATTEMPTUTCDATE
			   ,UPDATERESULT
			   ,UPDATELOG
			   )

			Select INSTALLATIONGUID 
			,CHAR_TO_UUID('96076138-3DE7-4018-93DC-84BD417081D6') --latest deploymentGUID
			,TRUE
			,CURRENT_TIMESTAMP
			,NULL
			,NULL
			,NULL
			,NULL
			from INSTALLATION
			where UUID_TO_CHAR(INSTALLATIONGUID) =  'DB390DD5-02C7-4594-9260-5FB1FF5961DC'; 
