      	INSERT INTO INSTALLATIONDEPLOYMENT
			   (INSTALLATIONGUID
			   ,DEPLOYMENTGUID
			   ,ISAVAILABLE
			   ,AVAILABLEUTCDATE
			   ,UPDATEDUTCDATE
			   ,LASTATTEMPTUTCDATE
			   ,UPDATERESULT
			   ,UPDATELOG
			   )

			Select INSTALLATIONGUID 
			,CHAR_TO_UUID('04B2F70A-EE58-4018-92C0-B108621F9014')
			,TRUE
			,CURRENT_TIMESTAMP
			,NULL
			,NULL
			,NULL
			,NULL
			from INSTALLATION;   
