set term ^ ;

EXECUTE BLOCK
AS
DECLARE VARIABLE aCountryGUID GUID;
BEGIN
    select gen_uuid() from RDB$Database into :aCountryGUID;
    
    INSERT INTO COUNTRY (COUNTRYGUID, ABBREVIATION, DESCRIPTION)
    VALUES (
        :aCountryGUID, 
        'US','United States'
    );


 --US States
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'AK', 'Alaska', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'AL', 'Alabama', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'AR', 'Arkansas', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'AZ', 'Arizona', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'CA', 'California', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'CO', 'Colorado', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'CT', 'Connecticut', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'DE', 'Delaware', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'FL', 'Florida', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'GA', 'Georgia', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'HI', 'Hawaii', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'IA', 'Iowa', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'ID', 'Idaho', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'IL', 'Illinois', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'IN', 'Indiana', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'KS', 'Kansas', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'KY', 'Kentucky', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'LA', 'Louisiana', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MA', 'Massachusetts', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MD', 'Maryland', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'ME', 'Maine', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MI', 'Michigan', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MN', 'Minnesota', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MO', 'Missouri', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MS', 'Mississippi', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MT', 'Montana', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NC', 'North Carolina', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'ND', 'North Dakota', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NE', 'Nebraska', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NH', 'New Hampshire', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NJ', 'New Jersey', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NM', 'New Mexico', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NV', 'Nevada', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NY', 'New York', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'OH', 'Ohio', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'OK', 'Oklahoma', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'OR', 'Oregon', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'PA', 'Pennsylvania', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'RI', 'Rhode Island', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'SC', 'South Carolina', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'SD', 'South Dakota', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'TN', 'Tennessee', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'TX', 'Texas', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'UT', 'Utah', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'VA', 'Virginia', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'VT', 'Vermont', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'WA', 'Washington', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'WI', 'Wisconsin', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'WV', 'West Virginia', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'WY', 'Wyoming', :aCountryGUID);

-- Canadian Provinces
    select gen_uuid() from RDB$Database into :aCountryGUID;
    
    INSERT INTO COUNTRY (COUNTRYGUID, ABBREVIATION, DESCRIPTION)
    VALUES (
        :aCountryGUID, 
       'CA','Canada'
    );
    

INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'AB', 'Alberta', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'BC', 'British Columbia', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'MB', 'Manitoba', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NB', 'New Brunswick', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NL', 'Newfoundland and Labrador', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NS', 'Nova Scotia', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NT', 'Northwest Territories', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'NU', 'Nunavut', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'ON', 'Ontario', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'PE', 'Prince Edward Island', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'QC', 'Quebec', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'SK', 'Saskatchewan', :aCountryGUID);
INSERT INTO STATEPROVINCE (STATEPROVINCEGUID, ABBREVIATION, DESCRIPTION, COUNTRYGUID) VALUES (gen_uuid(), 'YT', 'Yukon', :aCountryGUID);


END
^

set term ; ^






