SELECT i.devicefingerprint, d.UPDATEVERSION, uuid_to_char(r.INSTALLATIONGUID), r.DEPLOYMENTGUID, r.ISAVAILABLE, r.UPDATEDUTCDATE,
    r.LASTATTEMPTUTCDATE, r.UPDATERESULT, r.UPDATELOG, r.AVAILABLEUTCDATE,
    r.RECEIVEDUTCDATE
FROM INSTALLATIONDEPLOYMENT r
join installation i on i.INSTALLATIONGUID = r.INSTALLATIONGUID
join deployment d on r.DEPLOYMENTGUID = d.DEPLOYMENTGUID
--where i.DEVICEFINGERPRINT 