SELECT i.devicefingerprint, d.UPDATEVERSION, uuid_to_char(r.INSTALLATIONGUID) as InstallationGUID, uuid_to_char(r.DEPLOYMENTGUID) as DeploymentGUID, r.ISAVAILABLE, r.UPDATEDUTCDATE,
    r.LASTATTEMPTUTCDATE, r.UPDATERESULT, r.UPDATELOG, r.AVAILABLEUTCDATE,
    r.RECEIVEDUTCDATE
FROM INSTALLATIONDEPLOYMENT r
join installation i on i.INSTALLATIONGUID = r.INSTALLATIONGUID
join deployment d on r.DEPLOYMENTGUID = d.DEPLOYMENTGUID
--where i.DEVICEFINGERPRINT 

--disable update for everyone but LarryH
--update INSTALLATIONDEPLOYMENT 
--set IsAvailable = False 
--where uuid_to_char(DEPLOYMENTGUID) = 'C098C1F0-16E8-4214-A0CB-EE4AD7BC5507'
--and uuid_to_char(INSTALLATIONGUID) <> '3B72F928-4B46-4098-942C-5309CC38ACF3'